## NUMPY VERSION

In [3]:
import numpy as n
print(f'The Numpy version is {n.version.version}')

The Numpy version is 1.19.2


## LIST OF NUMERIC VALUES TO 1D NUMPY ARRAY

In [28]:
lst= [1,5,3,6]
nmpy= n.array(lst)
print(nmpy)

[1 5 3 6]


## ARRAY WITH VALUES FROM 12 TO 38

In [30]:
n.arange(12,39)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

## LIST AND TUPLE INTO ARRAY

In [35]:
tpl= (1,2,3,4)
lst1= [1,4,6,3]
print(n.array(tpl))
print(n.array(lst1))

[1 2 3 4]
[1 4 6 3]


## NUMBER,LENGTH IN BYTES AND BYTE CONSUMED BY ELEMENTS IN AN ARRAY 

In [47]:
arr= n.arange(12,39)
print(f'The length of the array is :{len(arr)}')
print(f'In the array {arr} one element consumes {arr.itemsize} bytes and a total of {arr.nbytes} bytes is being consumed as a whole.')

The length of the array is :27
In the array [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38] one element consumes 4 bytes and a total of 108 bytes is being consumed as a whole.


## COMPARE TWO ARRAYS

In [76]:
arr= n.array([1,6,8,10,2])
arr1= n.array([2,44,8,9,6])
g=n.greater(arr,arr1)
l=n.less(arr,arr1)
e= n.equal(arr,arr1)
print('Element wise comparison=')
print(f'aar>arr1: \n{g}')
print(f'aar<arr1: \n{l}')
print(f'aar=arr1: \n{e}')

Element wise comparison=
aar>arr1: 
[False False False  True False]
aar<arr1: 
[ True  True False False  True]
aar=arr1: 
[False False  True False False]


## NUMBER OF NON-ZERO ELEMENTS

In [85]:
arr2= n.array([1,5,0,6,2,0])
print(f'The number of non-zero elements in the array= {n.count_nonzero(arr2)}')

The number of non-zero elements in the array= 4


## NUMPY ARRAY IS EMPTY OR NOT

In [84]:
arr3= n.array([])
if len(arr3)==0:
    print('The Array is empty')
else:
    print('The Array is not empty')

The Array is empty


## POWERS OF ARRAY VALUES ELEMENT WISE

In [21]:
arr4= n.arange(1,10,0.5)
list(i**2 for i in arr4)

[1.0,
 2.25,
 4.0,
 6.25,
 9.0,
 12.25,
 16.0,
 20.25,
 25.0,
 30.25,
 36.0,
 42.25,
 49.0,
 56.25,
 64.0,
 72.25,
 81.0,
 90.25]

## STACK TWO ARRAYS

In [28]:
a1= n.linspace(1,20,50)
a2= n.linspace(21,40,50)
print(f'column: \n {n.column_stack((a1,a2))}')
print(f'row: \n {n.row_stack((a1,a2))}')

[[ 1.         21.        ]
 [ 1.3877551  21.3877551 ]
 [ 1.7755102  21.7755102 ]
 [ 2.16326531 22.16326531]
 [ 2.55102041 22.55102041]
 [ 2.93877551 22.93877551]
 [ 3.32653061 23.32653061]
 [ 3.71428571 23.71428571]
 [ 4.10204082 24.10204082]
 [ 4.48979592 24.48979592]
 [ 4.87755102 24.87755102]
 [ 5.26530612 25.26530612]
 [ 5.65306122 25.65306122]
 [ 6.04081633 26.04081633]
 [ 6.42857143 26.42857143]
 [ 6.81632653 26.81632653]
 [ 7.20408163 27.20408163]
 [ 7.59183673 27.59183673]
 [ 7.97959184 27.97959184]
 [ 8.36734694 28.36734694]
 [ 8.75510204 28.75510204]
 [ 9.14285714 29.14285714]
 [ 9.53061224 29.53061224]
 [ 9.91836735 29.91836735]
 [10.30612245 30.30612245]
 [10.69387755 30.69387755]
 [11.08163265 31.08163265]
 [11.46938776 31.46938776]
 [11.85714286 31.85714286]
 [12.24489796 32.24489796]
 [12.63265306 32.63265306]
 [13.02040816 33.02040816]
 [13.40816327 33.40816327]
 [13.79591837 33.79591837]
 [14.18367347 34.18367347]
 [14.57142857 34.57142857]
 [14.95918367 34.95918367]
 